# compare_analysis.R
#
# Purpose: Compare the results from the R-based analysis with a previous
#          analysis conducted in ArcGIS Pro.

# --- Load libraries --- #
library(dplyr)    # For data wrangling
library(readr)    # For reading CSV files efficiently
library(tidyr)    # For reshaping data (pivot_longer)
library(ggplot2)  # For plotting
library(sf)       # For loading vector data (site areas)

# --- Step 1: Load the datasets --- #

# Load the new results generated by the 'start.R' script
new_results_path <- "exports/n2k_disturbance_by_year_no_fire.csv"
new_results <- read_csv(new_results_path, show_col_types = FALSE)

# Load the old results from your ArcGIS Pro analysis
# You will need to find this file and update the path below.
# It might be a .csv, .txt, or .xlsx file.
# If it's an Excel file, you might use the readxl::read_excel() function.
old_results_path <- "imports/export_n2kloggedareas_20241030.csv"
old_results <- read_csv(old_results_path, show_col_types = FALSE)

# --- Load Site Area Data for Normalization --- #
cat("\n--- Loading Natura 2000 site areas for normalization ---\n")
n2k_gpkg_path <- "D:/GIS/Data/Raw Files/2024-05 Natura 2000 Europe/eea_v_3035_100_k_natura2000_p_2022_v01_r00/Natura2000_end2022.gpkg"
n2k_layername <- "NATURA2000SITES"

site_areas <- st_read(n2k_gpkg_path, layer = n2k_layername, quiet = TRUE) %>%
  st_drop_geometry() %>% # We only need the attribute table, not the shapes
  select(SITECODE, site_area_ha = AREAHA)

glimpse(site_areas)

# --- Step 2: Inspect and Understand the data --- #

cat("--- Structure of New R-based Results ---\n")
glimpse(new_results)

cat("\n--- Structure of Old ArcGIS Results ---\n")
glimpse(old_results)

# --- Step 3: Harmonize Data --- #
# Goal: Reshape the 'wide' ArcGIS data to a 'long' format to match the new data.

cat("\n--- Reshaping ArcGIS data from wide to long ---\n")

# 1. Select only the site identifier and the hectare columns from the old data.
# 2. Rename 'sitecode' to 'SITECODE' for consistency.
# 3. Use pivot_longer() to transform columns like 'ha2001', 'ha2002', etc.
#    into two new columns: 'year' and 'disturbed_ha_arcgis'.
# 4. Clean the new 'year' column by removing the "ha" prefix and converting to a number.
old_results_long <- old_results %>%
  select(SITECODE = sitecode, starts_with("ha20")) %>%
  pivot_longer(
    cols = -SITECODE,
    names_to = "year",
    values_to = "disturbed_ha_arcgis"
  ) %>%
  mutate(year = readr::parse_number(year))

glimpse(old_results_long)

# Clean up the new R-based results for comparison
# 1. Select the key columns and rename 'disturbed_ha' for clarity.
# 2. Filter out rows where year is 2000 or NA, as these don't represent
#    annual disturbances from the GFC dataset (which starts in 2001).
new_results_clean <- new_results %>%
  filter(year > 2000) %>%
  select(SITECODE, year, disturbed_ha_r = disturbed_ha)


# --- Step 4: Join Data for Comparison --- #
# We use a full_join to keep all records from both datasets. This helps us see
# if one analysis found disturbances where the other found none.
comparison_df <- full_join(
  new_results_clean,
  old_results_long,
  by = c("SITECODE", "year")
) %>%
  # A full join will create NAs where a site/year combo exists in one dataset
  # but not the other. This means zero disturbance, so we replace NA with 0.
  mutate(
    disturbed_ha_r = replace_na(disturbed_ha_r, 0),
    disturbed_ha_arcgis = replace_na(disturbed_ha_arcgis, 0)
  )

cat("\n--- Structure of the final joined comparison table ---\n")
glimpse(comparison_df)

cat("\n--- First 10 rows of the comparison table ---\n")
head(comparison_df, 10)

# --- Step 5: Analyze the Differences --- #

# Calculate the absolute difference in hectares for each site and year.
# A positive value means the R analysis found more disturbance.
# A negative value means the ArcGIS analysis found more disturbance.
comparison_df <- comparison_df %>%
  mutate(difference_ha = disturbed_ha_r - disturbed_ha_arcgis)

# Let's look at some summary statistics for the new 'difference_ha' column
cat("\n--- Summary of the differences (R - ArcGIS) in hectares ---\n")
summary(comparison_df$difference_ha)

cat("\n--- Top 10 largest positive differences (R > ArcGIS) ---\n")
print(comparison_df %>%
  arrange(desc(difference_ha)) %>%
  head(10))

cat("\n--- Top 10 largest negative differences (R < ArcGIS) ---\n")
print(comparison_df %>%
  arrange(difference_ha) %>%
  head(10))

# --- Step 6: Aggregate and Visualize by Member State --- #

cat("\n--- Aggregating differences by Member State ---\n")

# 1. Add a member_state column from the first two letters of SITECODE.
# 2. Group by member state and calculate the total disturbance from each
#    analysis and the net difference.
by_member_state <- comparison_df %>%
  mutate(member_state = substr(SITECODE, 1, 2)) %>%
  group_by(member_state) %>%
  summarise(
    total_r_ha = sum(disturbed_ha_r),
    total_arcgis_ha = sum(disturbed_ha_arcgis),
    net_difference_ha = sum(difference_ha),
    .groups = "drop"
  ) %>%
  # Filter out any potential edge cases with invalid site codes
  filter(nchar(member_state) == 2)

print(by_member_state)

# 3. Create a bar chart to visualize the net difference.
# We use reorder() to sort the countries by the difference, making it easier to read.
diff_plot <- ggplot(by_member_state, aes(x = reorder(member_state, net_difference_ha), y = net_difference_ha)) +
  geom_col(aes(fill = net_difference_ha > 0), show.legend = FALSE) +
  coord_flip() + # Flips axes to make country codes readable
  scale_fill_manual(values = c("TRUE" = "#d95f02", "FALSE" = "#1f78b4")) +
  labs(
    title = "Net Difference in Disturbance Area by Member State",
    subtitle = "Total Hectares (R Analysis - ArcGIS Analysis)",
    x = "Member State",
    y = "Net Difference (Hectares)"
  ) +
  theme_minimal()

print(diff_plot)

# Save the plot to a file for reports or presentations
ggsave("member_state_difference_plot.png", plot = diff_plot, width = 10, height = 8, dpi = 300)
cat("\n--- Member state difference plot saved to member_state_difference_plot.png ---\n")

# --- Step 7: Normalize Differences by Total Area and Visualize --- #

cat("\n--- Aggregating NORMALIZED differences by Member State ---\n")

# To normalize correctly, we need the total N2K area for each member state.
# First, calculate this total area from the site_areas data frame.
member_state_total_area <- site_areas %>%
  mutate(member_state = substr(SITECODE, 1, 2)) %>%
  group_by(member_state) %>%
  summarise(total_n2k_area_ha = sum(site_area_ha, na.rm = TRUE), .groups = "drop")

# Next, get the total disturbance calculated by each method per member state.
# We can reuse the 'by_member_state' data frame from the previous step.

# Join the disturbance totals with the area totals.
by_member_state_normalized <- by_member_state %>%
  left_join(member_state_total_area, by = "member_state") %>%
  # Calculate the net difference as a percentage of the country's total N2K area.
  # This shows the overall impact of the discrepancy relative to the area analyzed.
  mutate(
    net_diff_perc = (net_difference_ha / total_n2k_area_ha) * 100
  ) %>%
  # Filter out any countries with no area or invalid codes
  filter(total_n2k_area_ha > 0, nchar(member_state) == 2)

print(by_member_state_normalized[,c("member_state", "net_diff_perc")], n=27)

# Create a bar chart to visualize the NORMALIZED net difference.
diff_plot_normalized <- ggplot(by_member_state_normalized, aes(x = reorder(member_state, net_diff_perc), y = net_diff_perc)) +
  geom_col(aes(fill = net_diff_perc > 0), show.legend = FALSE) +
  coord_flip() +
  scale_fill_manual(values = c("TRUE" = "#d95f02", "FALSE" = "#1f78b4")) +
  labs(
    title = "Normalized Net Difference in Disturbance by Member State",
    subtitle = "Net Difference as a Percentage of Total Natura 2000 Area in Country",
    x = "Member State",
    y = "Net Difference (% of Total N2K Area)"
  ) +
  theme_minimal()

print(diff_plot_normalized)

# Save the plot
ggsave(
  "figures/member_state_normalized_difference_plot.png",
  plot = diff_plot_normalized,
  width = 10, height = 8, dpi = 300
)
cat("\n--- Member state normalized difference plot saved to member_state_normalized_difference_plot.png ---\n")
